spring:
  profile: local
  jpa:
    properties.hibernate:
      hbm2ddl.auto: update
      format_sql: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    showSql: true
    generate-ddl: true
  h2:
    console:
      enable: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE